server:
  port: 7000


dwz:
  image:
    path: /data/image/
  plugin:
    script:
      phantom: /data/script/phantom/bin/phantomjs
      crawlText: /data/script/phantom/crawlText.js
      screensHot: /data/script/phantom/screensHot.js



